### ISSUE TITLE
Specify a license

### ISSUE THREAD

**Issue by IgorDobryn** [yardstick/terraform-provider-mailtrap#5]
Hello,

Tank you for developing such a nice tool. Could you specify a license for this repository, please. 

You might find this [github doc](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) useful

**Comment by IgorDobryn** [comment]
@tchristie-meazure would you be able to do this update?

**Comment by tchristie-meazure** [comment]
Yep, MIT license is in the repo.
